name: Build Loongarch64 99pi sd image

on:
  push:
    branches: [main]

jobs:
  build-sd-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: ["loongarch64_99pi_tf", "loongarch64_99pi_wifi"]

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 8192
          swap-size-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: '/nix'

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 3G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Build SD Image for ${{ matrix.image_type }}
        run: |
          # 构建指定镜像
          nix build .#nixosConfigurations.${{ matrix.image_type }}.config.system.build.sdImage
          # 复制镜像文件到工作目录
          cp -v $(readlink result)/sd-image/*.img ${{ matrix.image_type }}.img

      - name: Upload SD Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_type }}-sd-image
          path: ${{ matrix.image_type }}.img
